version: '3'
services:
  culqi:
    image: cllaquec/culqi-prueba-api
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
