apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: culqi
  name: culqi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: culqi
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/docker-default: "true"
        io.kompose.service: culqi
    spec:
      containers:
        - env:
            - name: REDIS_HOST
              value: redis
          image: cllaquec/culqi-prueba-api:latest
          name: culqi
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
      restartPolicy: Always
